#/bin/sh
sed -i "" 's/あ/nv_46/g' data.txt
sed -i "" 's/い/nv_45/g' data.txt
sed -i "" 's/う/nv_44/g' data.txt
sed -i "" 's/え/nv_43/g' data.txt
sed -i "" 's/お/nv_42/g' data.txt
sed -i "" 's/か/nv_41/g' data.txt
sed -i "" 's/き/nv_40/g' data.txt
sed -i "" 's/く/nv_39/g' data.txt
sed -i "" 's/け/nv_38/g' data.txt
sed -i "" 's/こ/nv_37/g' data.txt
sed -i "" 's/さ/nv_36/g' data.txt
sed -i "" 's/し/nv_35/g' data.txt
sed -i "" 's/す/nv_34/g' data.txt
sed -i "" 's/せ/nv_33/g' data.txt
sed -i "" 's/そ/nv_32/g' data.txt
sed -i "" 's/た/nv_31/g' data.txt
sed -i "" 's/ち/nv_30/g' data.txt
sed -i "" 's/つ/nv_29/g' data.txt
sed -i "" 's/て/nv_28/g' data.txt
sed -i "" 's/と/nv_27/g' data.txt
sed -i "" 's/な/nv_26/g' data.txt
sed -i "" 's/に/nv_25/g' data.txt
sed -i "" 's/ぬ/nv_24/g' data.txt
sed -i "" 's/ね/nv_23/g' data.txt
sed -i "" 's/の/nv_22/g' data.txt
sed -i "" 's/は/nv_21/g' data.txt
sed -i "" 's/ひ/nv_20/g' data.txt
sed -i "" 's/ふ/nv_19/g' data.txt
sed -i "" 's/へ/nv_18/g' data.txt
sed -i "" 's/ほ/nv_17/g' data.txt
sed -i "" 's/ま/nv_16/g' data.txt
sed -i "" 's/み/nv_15/g' data.txt
sed -i "" 's/む/nv_14/g' data.txt
sed -i "" 's/め/nv_13/g' data.txt
sed -i "" 's/も/nv_12/g' data.txt
sed -i "" 's/や/nv_11/g' data.txt
sed -i "" 's/ゆ/nv_10/g' data.txt
sed -i "" 's/よ/nv_09/g' data.txt
sed -i "" 's/ら/nv_08/g' data.txt
sed -i "" 's/り/nv_07/g' data.txt
sed -i "" 's/る/nv_06/g' data.txt
sed -i "" 's/れ/nv_05/g' data.txt
sed -i "" 's/ろ/nv_04/g' data.txt
sed -i "" 's/わ/nv_03/g' data.txt
sed -i "" 's/を/nv_02/g' data.txt
sed -i "" 's/ん/nv_01/g' data.txt
sed -i "" 's/nv_01/あ/g' data.txt
sed -i "" 's/nv_02/い/g' data.txt
sed -i "" 's/nv_03/う/g' data.txt
sed -i "" 's/nv_04/え/g' data.txt
sed -i "" 's/nv_05/お/g' data.txt
sed -i "" 's/nv_06/か/g' data.txt
sed -i "" 's/nv_07/き/g' data.txt
sed -i "" 's/nv_08/く/g' data.txt
sed -i "" 's/nv_09/け/g' data.txt
sed -i "" 's/nv_10/こ/g' data.txt
sed -i "" 's/nv_11/さ/g' data.txt
sed -i "" 's/nv_12/し/g' data.txt
sed -i "" 's/nv_13/す/g' data.txt
sed -i "" 's/nv_14/せ/g' data.txt
sed -i "" 's/nv_15/そ/g' data.txt
sed -i "" 's/nv_16/た/g' data.txt
sed -i "" 's/nv_17/ち/g' data.txt
sed -i "" 's/nv_18/つ/g' data.txt
sed -i "" 's/nv_19/て/g' data.txt
sed -i "" 's/nv_20/と/g' data.txt
sed -i "" 's/nv_21/な/g' data.txt
sed -i "" 's/nv_22/に/g' data.txt
sed -i "" 's/nv_23/ぬ/g' data.txt
sed -i "" 's/nv_24/ね/g' data.txt
sed -i "" 's/nv_25/に/g' data.txt
sed -i "" 's/nv_26/は/g' data.txt
sed -i "" 's/nv_27/ひ/g' data.txt
sed -i "" 's/nv_28/ふ/g' data.txt
sed -i "" 's/nv_29/へ/g' data.txt
sed -i "" 's/nv_30/ほ/g' data.txt
sed -i "" 's/nv_31/ま/g' data.txt
sed -i "" 's/nv_32/み/g' data.txt
sed -i "" 's/nv_33/む/g' data.txt
sed -i "" 's/nv_34/め/g' data.txt
sed -i "" 's/nv_35/も/g' data.txt
sed -i "" 's/nv_36/や/g' data.txt
sed -i "" 's/nv_37/ゆ/g' data.txt
sed -i "" 's/nv_38/よ/g' data.txt
sed -i "" 's/nv_39/ら/g' data.txt
sed -i "" 's/nv_40/り/g' data.txt
sed -i "" 's/nv_41/る/g' data.txt
sed -i "" 's/nv_42/れ/g' data.txt
sed -i "" 's/nv_43/え/g' data.txt
sed -i "" 's/nv_44/う/g' data.txt
sed -i "" 's/nv_45/を/g' data.txt
sed -i "" 's/nv_46/ん/g' data.txt
